import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>isaacson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Hey, im Joey
        </h1>

        <h5 className={styles.description}>
          Design manager at Coinbase
        </h5>

        <p className={styles.description}>
          Leading my team of 7 across.
        </p>

      </main>

      <footer className={styles.footer}>
       designed and built by joey isaacson</footer>
        </a>
      </footer>
    </div>
  );
}
